// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlmncesgjavqfrxxojfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbW5jZXNnamF2cWZyeHhvamZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDI2OTUsImV4cCI6MjA2NTY3ODY5NX0.zV1Yct1W8la9qqL8FO5hU3dnUm1WtunttYlDLzasymg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);